version: "3"

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data

  img:
    build: img
    env_file: img/.env.sample
    environment:
      - DATABASE_URL=postgres://postgres@db/picture_development
    command: yarn start
    volumes:
      - ./img:/app
    ports:
      - "4000:4000"
    depends_on:
      - db

  web:
    build: web
    env_file: web/.env.sample
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
    command: bundle exec rails server -p 3000 -b "0.0.0.0"
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - img

volumes:
  db:
